<div class="page-title">
    <h1><?php echo $this->__('Você retornou ao nosso site') ?></h1>
</div>
<p>Você acabou de realizar uma tentativa da pagamento.</p>
<p>Em breve você será notificado sobre o status do seu pedido.</p>
<?php $session = Mage::getSingleton('checkout/session'); ?>
<?php $orderId = $session->getLastRealOrderId() ?>
<?php if ($orderId):?>
    <p><?php echo $this->__('Your order # is: %s.', sprintf('<a href="%s">%s</a>', Mage::getUrl('sales/order/view', array('order_id'=>$orderId)), $orderId)) ?></p>
    <p><?php echo $this->__('You will receive an order confirmation email with details of your order and a link to track its progress.') ?></p>
<?php endif;?>