<?php
/**
 * Paybras
 *
 * @category   Payments
 * @package    Xpd_Paybras
 * @license    OSL v3.0
 */
 ?>
 <?php
    $_code = $this->getMethodCode();
    //feito para ter compatibilidade com o OneStepCheckout
    $route = $this->getRequest()->getRequestedRouteName();
    if($route == 'onestepcheckout') {
        $fieldCode = '['.$_code.']';
    }
    else {
        $fieldCode = '';
    };
?>

<?php $cpfForce = Mage::getStoreConfig('payment/paybrasboleto/forcecpf') == '' || Mage::getStoreConfig('payment/paybrasboleto/forcecpf') == 0 || Mage::getStoreConfig('payment/paybrasboleto/forcecpf') == '0' ? 0 : 1; ?>

<?php if($cpfForce):?>
<script type="text/javascript">
new MaskedInput('input[name="payment[cc_cpftitular]"]', '999.999.999-99');

Validation.add('cpftitular','CPF Inválido',function(valueCPF) {
    var cpf = valueCPF.replace(/[^\d]+/g,'');
    if(cpf == '') return true;
    while(cpf.length < 11) cpf = "0"+ cpf;
    var expReg = /^0+$|^1+$|^2+$|^3+$|^4+$|^5+$|^6+$|^7+$|^8+$|^9+$/;
    var a = [];
    var b = new Number;
    var c = 11;
    for (i=0; i<11; i++){
            a[i] = cpf.charAt(i);
            if (i < 9) b += (a[i] * --c);
    }
    if ((x = b % 11) < 2) {
            a[9] = 0
    } 
    else {
            a[9] = 11-x
    }

    b = 0;
    c = 11;

    for (y=0; y<10; y++) b += (a[y] * c--);
    if ((x = b % 11) < 2) {
            a[10] = 0;
    }
    else {
            a[10] = 11-x;
    }
    if ((cpf.charAt(9) != a[9]) || (cpf.charAt(10) != a[10]) || cpf.match(expReg)) return false;
    return true;
});
</script>
<?php endif; ?>

<fieldset class="form-list">
<ul id="payment_form_<?php echo $_code; ?>" style="display:none;">
	<li>
		<!--p><img src="<?php echo $this->getSkinUrl(); ?>"/></p-->
		<p><?php echo Mage::getStoreConfig('payment/paybrasboleto/textboleto'); ?></p>
	</li>
	<?php if($cpfForce): ?>
	<li id="<?php echo $_code ?>_cc_cpftitular_div" <?php if(!$cpfForce): ?>style="display: none;"<?php endif; ?>>
        <label for="<?php echo $_code ?>_cc_cpftitular" class="required"><em>*</em><?php echo $this->__("TAX/VAT") ?></label><br />
        <div class="input-box">
            <div class="v-fix">
                <input type="text" title="<?php echo $this->__('TAX/VAT') ?>" class="input-text cpftitular required-entry" id="<?php echo $_code ?>_cc_cpftitular" name="payment[cc_cpftitular]" value="" maxlength="14" />
            </div>
        </div>
    </li>
    <?php endif; ?>
</ul>
</fieldset>